### ISSUE TITLE
Finished the assignment

### ISSUE THREAD

**Issue by Cantfirmed** [htl-perg-2019-20-5ahif/contact-list-exercise-Cantfirmed#1]
Implemented the four swagger paths

**Comment by rstropek** [comment]
Please avoid checking in unnecessary files (e.g. *.vs*, *bin*).

**Comment by rstropek** [comment]
Nearly. Spec said *contains*, not *equals* for find-by-name. However, rest looks quite good. The extra point is yours.

Greetings,
Rainer Stropek
